2020-05-08 12:35:33 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-08 12:35:51 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for bom_forecast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-08 12:36:03 WARNING (MainThread) [homeassistant.setup] Setup of coronavirus is taking over 10 seconds.
2020-05-08 12:36:03 WARNING (MainThread) [homeassistant.setup] Setup of updater is taking over 10 seconds.
2020-05-08 12:36:03 WARNING (MainThread) [homeassistant.setup] Setup of counter is taking over 10 seconds.
2020-05-08 12:36:03 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.
2020-05-08 12:36:03 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2020-05-08 12:36:03 WARNING (MainThread) [homeassistant.setup] Setup of person is taking over 10 seconds.
2020-05-08 12:36:03 WARNING (MainThread) [homeassistant.components.weather] Setup of weather platform bom is taking over 10 seconds.
2020-05-08 12:36:03 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform iss is taking over 10 seconds.
2020-05-08 12:36:03 ERROR (MainThread) [homeassistant.components.coronavirus] Timeout fetching coronavirus data
2020-05-08 12:36:08 WARNING (MainThread) [homeassistant.components.mobile_app.notify] Found duplicate device name Aruna Gupta’s iPhone
2020-05-08 12:36:08 WARNING (MainThread) [homeassistant.components.mobile_app.notify] Found duplicate device name Aruna Gupta’s iPhone
2020-05-08 12:41:17 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 288, in async_add_entities
    for entity in new_entities
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 285, in <listcomp>
    self._async_add_entity(  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/coronavirus/sensor.py", line 22, in <genexpr>
    for info_type in SENSORS
  File "/usr/src/homeassistant/homeassistant/components/coronavirus/sensor.py", line 37, in __init__
    self.name = f"{coordinator.data[country].country} Coronavirus {info_type}"
TypeError: 'NoneType' object is not subscriptable
2020-05-08 12:41:17 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 288, in async_add_entities
    for entity in new_entities
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 285, in <listcomp>
    self._async_add_entity(  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/coronavirus/sensor.py", line 22, in <genexpr>
    for info_type in SENSORS
  File "/usr/src/homeassistant/homeassistant/components/coronavirus/sensor.py", line 37, in __init__
    self.name = f"{coordinator.data[country].country} Coronavirus {info_type}"
TypeError: 'NoneType' object is not subscriptable
2020-05-08 12:41:17 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 288, in async_add_entities
    for entity in new_entities
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 285, in <listcomp>
    self._async_add_entity(  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/coronavirus/sensor.py", line 22, in <genexpr>
    for info_type in SENSORS
  File "/usr/src/homeassistant/homeassistant/components/coronavirus/sensor.py", line 37, in __init__
    self.name = f"{coordinator.data[country].country} Coronavirus {info_type}"
TypeError: 'NoneType' object is not subscriptable
2020-05-08 12:41:20 WARNING (MainThread) [homeassistant.helpers.translation] hacs: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-08 12:41:21 WARNING (MainThread) [homeassistant.helpers.translation] hacs: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-08 12:41:24 WARNING (MainThread) [homeassistant.helpers.translation] hacs: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-08 12:41:25 WARNING (MainThread) [homeassistant.helpers.translation] hacs: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
